routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

//User Routes
Route::get('/', function () {
   // dd(Auth::user());
    return view('welcome');
});

Auth::routes();
Route::get('/courses/{slug}', [App\Http\Controllers\CourseController::class, 'index'])->name('course');
Route::get('/courses/{slug}/quizzes/{name}', [App\Http\Controllers\QuizController::class, 'index'])->name('quiz');
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Auth::routes();

Route::get('/home', 'App\Http\Controllers\HomeController@index')->name('home');




//Admin Routes
Route::group(['middleware' => ['auth','Admin']], function () {
    Route::get('admin/dashboard', 'App\Http\Controllers\Admin\HomeController@index')->name('dashboard');
    Route::get('admin', function(){
     return redirect()->route('dashboard');
    });
	Route::resource('admin/users', 'App\Http\Controllers\Admin\UserController', ['except' => ['show']]);
	Route::resource('admin/admins', 'App\Http\Controllers\Admin\AdminController', ['except' => ['show']]);
	Route::resource('admin/tracks', 'App\Http\Controllers\Admin\TrackController');
	Route::resource('admin/courses', 'App\Http\Controllers\Admin\CourseController');
	Route::resource('admin/videos', 'App\Http\Controllers\Admin\VideoController');
    Route::resource('admin/quizzes', 'App\Http\Controllers\Admin\QuizController');
    Route::resource('admin/questions', 'App\Http\Controllers\Admin\QuestionController');
    Route::resource('admin/track.courses', 'App\Http\Controllers\Admin\TrackCoursesController');
    //suppose we have foder videos inside courses folder //Route::resource('admin/courses.videos', 'App\Http\Controllers\Admin\QuestionController'); ?? why admin/courses/videos
	Route::get('admin/profile', ['as' => 'profile.edit', 'uses' => 'App\Http\Controllers\Admin\ProfileController@edit']);
           //as means alias(altenative) look like name('profile.edit')
    Route::put('admin/profile', ['as' => 'profile.update', 'uses' => 'App\Http\Controllers\Admin\ProfileController@update']);
    Route::put('admin/profile/password', ['as' => 'profile.password', 'uses' => 'App\Http\Controllers\Admin\ProfileController@password']);


    Route::get('upgrade', function () {return view('pages.upgrade');})->name('upgrade');
    Route::get('map', function () {return view('pages.maps');})->name('map');
    Route::get('icons', function () {return view('pages.icons');})->name('icons');
    Route::get('table-list', function () {return view('pages.tables');})->name('table');

});

app/Models/Video.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Video extends Model
{
    use HasFactory;
     protected $fillable=[
         'title','link','course_id'
        ];
       public function course(){//one to many between course & video
        return $this->belongsTo('App\Models\Course');
    }
}

app/Http/Controllers/Admin/VideoController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Video;
class VideoController extends Controller
{
    
    public function index()
    {
        $videos=Video::orderBy('id','desc')->paginate(15);
    return view('admin.videos.index',compact('videos'));
    }
    public function create()
    {
        return view('admin.videos.create');
    }

   
    public function store(Request $request)
    {
        $rules=[
            'title'=> 'required|min:5|max:150',
            'link'=> 'required|url',
            'course_id'=> 'required|integer',];
        $this->validate($request,$rules);
     if(Video::create($request->all())){
            return redirect()->route('videos.index')->with("mssg","Video succussfully Creates.");
     }else{
          // LOOK-----> 
          return redirect()->route('videos.create')->with("mssg","Try to Create this Video Again.");
     }
    }

    public function show(Video $video)
    {
        return view('admin.videos.show',compact('video'));
    }

    public function edit(Video $video)
    {
        return view('admin.videos.edit',compact('video'));
    }

    public function update(Request $request,Video $video)
    {
        $rules=[
            'title'=> 'required|min:5|max:150',
            'link'=> 'required|url',
            'course_id'=> 'required|integer',];
        $this->validate($request,$rules);
     if($video->update($request->all())){
            return redirect()->route('videos.index')->with("mssg","Video succussfully Updates.");
     }else{
          // LOOK-----> 
          return redirect()->route('videos.edit',$video)->with("mssg","Try to Update this Video Again.");
     }
    }

    public function destroy(Video $video)
    {
        $video->delete();
        return redirect()->route('videos.index')->with("mssg","Video succussfully deleted.");
    }
}

resources/views/admin/videos/create.blade.php
@extends('layouts.app', ['title' => __('Video_Create')])

@section('content')
    @include('admin.users.partials.header', [
        'title' => __('New video') . ' ',
        'description' => __('Hi '.auth()->user()->name .' can create a new video'),
        'class' => 'col-lg-12'
    ])

    <div class="container-fluid mt--7">
        <div class="row">
            <div class="col-xl-12 order-xl-1">
                <div class="card bg-secondary shadow">
                    <div class="card-header bg-white border-0">
                        <div class="row align-items-center">
                            <h3 class="mb-0"><i class="fa fa-video" aria-hidden="true"></i> {{ __('Create Video') }}</h3>
                        </div>
                    </div>
    <div class="col-12"> </div>
             @include('includes.errors')
             @include('includes.message')
                <form role="form" method="POST" action="{{ route('videos.store') }}">
                            @csrf
                            <div class="form-group{{ $errors->has('title') ? ' has-danger' : '' }}">
                                <div class="input-group input-group-alternative mb-5">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text"><i class="ni ni-hat-3"></i></span>
                                    </div>
                                    <input class="form-control{{ $errors->has('title') ? ' is-invalid' : '' }}" placeholder="{{ __('title') }}" type="text" name="title" value="{{ old('title') }}" required autofocus>
                                </div>
                                @if ($errors->has('title'))
                                    <span class="invalid-feedback" style="display: block;" role="alert">
                                        <strong>{{ $errors->first('title') }}</strong>
                                    </span>
                                @endif
                            </div>
                            <div class="form-group{{ $errors->has('link') ? ' has-danger' : '' }}">
                                <div class="input-group input-group-alternative mb-5">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text"><i class="fas fa-link"></i></span>
                                    </div>
                                    <input class="form-control{{ $errors->has('link') ? ' is-invalid' : '' }}" placeholder="{{ __('link') }}" type="link" name="link" value="{{ old('link') }}" required>
                                </div>
                                @if ($errors->has('link'))
                                    <span class="invalid-feedback" style="display: block;" role="alert">
                                        <strong>{{ $errors->first('link') }}</strong>
                                    </span>
                                @endif
                            </div>
                              <div class="form-group{{ $errors->has('course_id') ? ' has-danger' : '' }}">
                                <div class="input-group input-group-alternative mb-5">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text"><i class="fa fa-book" aria-hidden="true" ></i></span>
                                    </div>
                                   <select class="form-control" name="course_id" class="form-control" required>
                                   <option value='' disabled selected>{{ __('course_id') }}</option>
                                   @foreach (\App\Models\Course::orderBy('id','desc')->get() as $course )
                                       <option value='{{$course->id}}'>{{$course->title}}</option>
                                   @endforeach
                                   </select>
                                  </div>
                                  </div>
                            <div class="text-center">
                                <button type="submit" class="btn btn-block btn-success mt-5">{{ __('Create account') }}</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>

        @include('layouts.footers.auth')
    </div>
@endsection

resources/views/admin/videos/edit.blade.php
@extends('layouts.app', ['title' => __('Video_Edit')])

@section('content')
    @include('admin.users.partials.header', [
        'title' => __('Edit video') . ' ',
        'description' => __('Hi '.auth()->user()->name .' can Edit a new video'),
        'class' => 'col-lg-12'
    ])

    <div class="container-fluid mt--7">
        <div class="row">
            <div class="col-xl-12 order-xl-1">
                <div class="card bg-secondary shadow">
                    <div class="card-header bg-white border-0">
                        <div class="row align-items-center">
                            <h3 class="mb-0"><i class="fa fa-video" aria-hidden="true"></i> {{ __('Edit Video') }}</h3>
                        </div>
                    </div>
    <div class="col-12"> </div>
             @include('includes.errors')
             @include('includes.message')
                <form role="form" method="POST" action="{{ route('videos.update',$video) }}">
                            @csrf
                            @method('PATCH')
                            <div class="form-group{{ $errors->has('title') ? ' has-danger ' : '' }}">
                                <div class="input-group input-group-alternative mb-5">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text"><i class="ni ni-hat-3"></i></span>
                                    </div>
                                    <input class="form-control{{ $errors->has('title') ? ' is-invalid' : '' }}" placeholder="{{ __('title') }}" type="text" name="title" value="{{$video->title}}" required autofocus>
                                  {{-- <div class="valid-feedback">Valid.</div>
      <div class="invalid-feedback">Please fill out this field.</div> --}}
                                </div>
                                @if ($errors->has('title'))
                                    <span class="invalid-feedback" style="display: block;" role="alert">
                                        <strong>{{ $errors->first('title') }}</strong>
                                    </span>
                                @endif
                            </div>
                            <div class="form-group{{ $errors->has('link') ? ' has-danger' : '' }}">
                                <div class="input-group input-group-alternative mb-5">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text"><i class="fas fa-link"></i></span>
                                    </div>
                                    <input class="form-control{{ $errors->has('link') ? ' is-invalid' : '' }}" placeholder="{{ __('link') }}" type="link" name="link" value="{{$video->link}}" required>
                                </div>
                                @if ($errors->has('link'))
                                    <span class="invalid-feedback" style="display: block;" role="alert">
                                        <strong>{{ $errors->first('link') }}</strong>
                                    </span>
                                @endif
                            </div>

                              <div class="form-group{{ $errors->has('course_id') ? ' has-danger' : '' }}">
                                <div class="input-group input-group-alternative mb-5">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text"><i class="fa fa-book" aria-hidden="true" ></i></span>
                                    </div>
                                   <select class="form-control" name="course_id" class="form-control" required>
                                   @foreach (\App\Models\Course::orderBy('id','desc')->get() as $course )
                                       <option value='{{$course->id}}' {{($course->id==$video->course_id)?'selected':''}}>{{$course->title}}</option>
                                   @endforeach
                                   </select>
                                  </div>
                                </div>

                            <div class="text-center">
                                <button type="submit" class="btn btn-block btn-success mt-5">{{ __('Create account') }}</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>

        @include('layouts.footers.auth')
    </div>
@endsection

resources/views/admin/videos/index.blade.php
@extends('layouts.app', ['title' => __('Index_Video')])

@section('content')
    @include('admin.users.partials.header', [
        'title' => __('Index_Video') . ' '. auth()->user()->name,
        'description' => __('Index_Video'),
        'class' => 'col-lg-7'
    ])
<div class="container-fluid mt--7">
    <div class="row">
        <div class="col">
            <div class="card shadow">
                <div class="card-header border-0">
                    <div class="row align-items-center">
                        <div class="col-8">
                            <h3 class="mb-0"><i class="fa fa-video" aria-hidden="true"  style="color:#5f9"></i> Videos</h3>
                        </div>
                        <div class="col-4 text-right">
                            <a href="{{ route('videos.create') }}" class="btn btn-sm btn-primary">Add Video</a>
                        </div>
                    </div>
                </div>

                <div class="col-12"> </div>
             @include('includes.errors')
             @include('includes.message')
            {{--  class offset-sm-1   --}}
                <div class="table-responsive">
                    <table class="table align-items-center table-flush">
                        <thead class="thead-light">
                            <tr>
                                <th scope="col">Title</th>
                                <th scope="col">Course Name</th>
                                <th scope="col">Creation Date</th>
                                <th scope="col" class="text-right"></th>
                            </tr>
                    </thead>
                    <tbody>
                        {{--  @php echo $users @endphp  --}}
                         @foreach ($videos as $video)
                                <tr>
                                  <td> <a href="{{route('videos.show',$video)}}">{{$video->title}}</a></td>
                                    <td>
                                    <a href="{{route('courses.show',$video->course)}}">{{$video->course->title}}</a>
                                    </td>
                                  
                                    {{-- <td>{{$video->created_at->diffForHumans()}}</td> --}}
                                     <td>{{$video->created_at->format('d/m/Y N:1')}}</td>
                              
                                    <td class="text-right">
                                           <div class="dropdown">
                                            <a class="btn btn-sm btn-icon-only text-light" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                <i class="fas fa-ellipsis-v"></i>
                                            </a>
                                            <div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow">
                                                        <form method="POST" action="{{route('videos.destroy',$video->id)}}">
                                                            @csrf
                                                            @method('DELETE')
                                                            <a class="dropdown-item" href="{{route('videos.edit',$video->id)}}">Edit</a>

                                                                <a class="dropdown-item" onclick="confirm('Are You Sure you want to Delete this video')?this.parentElement.submit():'' ">
                                                                Delete </a>
                                                          </form>
                                                          
                                                </div>
                                        </div>
                                    </td>
                               </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
      <div class="card-footer" style="text-align: center;">
            <nav class="" aria-label="...">
              {{$videos->links()}}
            </nav>
      </div>
    </div>
</div>
</div>
@include('layouts.footers.auth')
</div> 
@endsection

   

resources/views/admin/videos/show.blade.php
@extends('layouts.app', ['title' => __('Preview Video')])

@section('content')
    @include('admin.users.partials.header', [
        'title' => __('New video') . ' ',
        'description' => __('Hi '.auth()->user()->name .'You can Preview Video'),
        'class' => 'col-lg-12'
    ])

    <div class="container-fluid mt--7">
        <div class="row">
            <div class="col-xl-12 order-xl-1">
                <div class="card bg-secondary shadow">
                    <div class="card-header bg-white border-0">
                        <div class="row align-items-center">
                            <div class="col-8">
                               <h3 class="mb-0"><i class="fa fa-video" aria-hidden="true"></i> {{ __('Show Video') }}</h3>
                            </div>
                            <div class="col-4 text-right">
                                <a href="{{ route('admins.create') }}" class="btn btn-sm btn-primary">Add Admin</a>
                            </div> 
                        </div>
                    </div>
                    <div class="col-12"> </div>
                    @include('includes.errors')
                    @include('includes.message')
                        <div class="card-body">
                            <h1 class="text-muted">Title: {{$video->title}}</h1>
                            <iframe src="{{$video->link}}" frameborder="0" allow="accelerometor; autoplay;encrypted-media;gyroscope;pictue-in-picture allowfullscreen" width="100%" height="650">
                            </iframe> 
                        </div>
                </div>
           </div>
        </div>
     </div>

        @include('layouts.footers.auth')
    </div>
@endsection