routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

//User Routes
Route::get('/', function () {
   // dd(Auth::user());
    return view('welcome');
});

Auth::routes();
Route::get('/courses/{slug}', [App\Http\Controllers\CourseController::class, 'index'])->name('course');
Route::get('/courses/{slug}/quizzes/{name}', [App\Http\Controllers\QuizController::class, 'index'])->name('quiz');
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Auth::routes();

Route::get('/home', 'App\Http\Controllers\HomeController@index')->name('home');




//Admin Routes
Route::group(['middleware' => ['auth','Admin']], function () {
    Route::get('admin/dashboard', 'App\Http\Controllers\Admin\HomeController@index')->name('dashboard');
    Route::get('admin', function(){
     return redirect()->route('dashboard');
    });
	Route::resource('admin/users', 'App\Http\Controllers\Admin\UserController', ['except' => ['show']]);
	Route::resource('admin/admins', 'App\Http\Controllers\Admin\AdminController', ['except' => ['show']]);
	Route::resource('admin/tracks', 'App\Http\Controllers\Admin\TrackController');
	Route::resource('admin/courses', 'App\Http\Controllers\Admin\CourseController');
	Route::resource('admin/videos', 'App\Http\Controllers\Admin\VideoController');
    Route::resource('admin/quizzes', 'App\Http\Controllers\Admin\QuizController');
    Route::resource('admin/questions', 'App\Http\Controllers\Admin\QuestionController');
    Route::resource('admin/track.courses', 'App\Http\Controllers\Admin\TrackCoursesController');
    //suppose we have foder videos inside courses folder //Route::resource('admin/courses.videos', 'App\Http\Controllers\Admin\QuestionController'); ?? why admin/courses/videos
	Route::get('admin/profile', ['as' => 'profile.edit', 'uses' => 'App\Http\Controllers\Admin\ProfileController@edit']);
           //as means alias(altenative) look like name('profile.edit')
    Route::put('admin/profile', ['as' => 'profile.update', 'uses' => 'App\Http\Controllers\Admin\ProfileController@update']);
    Route::put('admin/profile/password', ['as' => 'profile.password', 'uses' => 'App\Http\Controllers\Admin\ProfileController@password']);


    Route::get('upgrade', function () {return view('pages.upgrade');})->name('upgrade');
    Route::get('map', function () {return view('pages.maps');})->name('map');
    Route::get('icons', function () {return view('pages.icons');})->name('icons');
    Route::get('table-list', function () {return view('pages.tables');})->name('table');

});

app/Models/Track.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Track extends Model
{
    use HasFactory;
     protected $fillable=[
         'name',
        ];
    public function users(){//many to many between course & user
        return $this->belongsToMany('App\Models\User');
    }
    public function courses(){//one to many between track & course
        return $this->hasMany('App\Models\Course');
    }
}

app/Http/Controllers/Admin/TrackController.php
<?php

namespace App\Http\Controllers\Admin;
use App\Http\Controllers\Controller;
use App\Models\Track;
use Illuminate\Http\Request;
//use Carbon\Carbon;//for date
class TrackController extends Controller
{
    public function index()
    {
        $tracks=Track::orderBy('id','desc')->paginate(20);
        return view('admin.tracks.index',compact('tracks'));
    }
    public function store(Request $request)
    { //'created_at'=>Carbon::now()
        $rules=[
            'name'=> 'required|min:5|max:30',
        ];
        $this->validate($request,$rules);
        if(Track::create($request->all())){
            return redirect()->route('tracks.index')->with("mssg",'Track succussfully created.');
        }else{
            return redirect()->route('tracks.index')->with("mssg",'Try Again.');
        }
           
    }

    public function show(Track $track)
    {
        return view('admin.tracks.show',compact('track'));
    }
    // public function show(Product $product)
    // {
    //     return ProductDetailResource::make($product);
    // }
    public function edit(Track $track)
    {
        return view('admin.tracks.edit',compact('track'));
    }
    public function update(Request $request, Track $track)
    {
        $rules=[
            'name'=> 'required|min:5|max:30',
        ];
        $this->validate($request,$rules);
           $track->update([
              'name'=> $request->name,
           ]);
         // if($request->has('name')){$track->name=$request->name; }
         // if($track->isDerty()){$track->save();dd("ali");}//if changed
           if( $track->update($request->all())){
              return redirect()->route('tracks.index')->with("mssg","Track succussfully Updated.");
         }else{
              // LOOK-----> 
              return redirect()->route('tracks.edit',$track->id)->with("mssg","Try Update Again.");
         }
    }
    public function destroy(Track $track)
    {
        $track->delete();
        return redirect()->route('tracks.index')->with("mssg","Track succussfully deleted.");
        //->withStatus(__('User succussfully deleted.'));
    }
}
//->with("mssg","Restore Done Now you can delete thi Row :)");  ---->Invoking--->  <p class="mssg">{{session('mssg')}}</p>
//بالمختصر بمرق وسطاءاغراض وبالفرمات بمرق كوائن

resources/views/admin/tracks/courses/create.blade.php
@extends('layouts.app', ['title' => __('Course_Managment')])

@section('content')
    @include('admin.users.partials.header', [
        'title' => __('New Course innside track') . ' ',
        'description' => __('Hi '.auth()->user()->name .'You can Create Course inside Track'),
        'class' => 'col-lg-12'
    ])

    <div class="container-fluid mt--7">
        <div class="row">
            <div class="col-xl-12 order-xl-1">
                <div class="card bg-secondary shadow">
                    <div class="card-header bg-white border-0">
                        <div class="row align-items-center">
                            <h3 class="mb-0">{{ __('Create Course') }}</h3>
                        </div>
                    </div>
<h1>Createe </h1>
                <form role="form" method="POST" action="{{ route('track.courses.store',$track) }}" enctype="multipart/form-data">
                            @csrf
{{-- Title --}}
                            <div class="form-group{{ $errors->has('title') ? ' has-danger' : '' }}">
                                <div class="input-group input-group-alternative mb-5">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text"><i class="ni ni-hat-3"></i></span>
                                    </div>
                                    <input class="form-control{{ $errors->has('title') ? ' is-invalid' : '' }}" placeholder="{{ __('title') }}" type="text" name="title" value="{{ old('title') }}" required autofocus>
                                </div>
                                @if ($errors->has('title'))
                                    <span class="invalid-feedback" style="display: block;" role="alert">
                                        <strong>{{ $errors->first('title') }}</strong>
                                    </span>
                                @endif
                            </div>
{{-- Title --}} 

                             <div class="form-group{{ $errors->has('link') ? ' has-danger' : '' }}">
                                <div class="input-group input-group-alternative mb-5">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text"><i class="fas fa-link"></i></span>
                                    </div>
                                    <input class="form-control{{ $errors->has('link') ? ' is-invalid' : '' }}" placeholder="{{ __('link') }}" type="link" name="link" required>
                                </div>
                                @if ($errors->has('link'))
                                    <span class="invalid-feedback" style="display: block;" role="alert">
                                        <strong>{{ $errors->first('link') }}</strong>
                                    </span>
                                @endif
                            </div>
                                <div class="form-group{{ $errors->has('image') ? ' has-danger' : '' }}">
                                <div class="input-group input-group-alternative mb-5">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text"><i class='far fa-image' style="font-size:20px"></i></span>
                                    </div>
                                    <input class="form-control{{ $errors->has('image') ? ' is-invalid' : '' }}" placeholder="{{ __('image') }}" type="file" name="image" required>
                                </div>
                                @if ($errors->has('image'))
                                    <span class="invalid-feedback" style="display: block;" role="alert">
                                        <strong>{{ $errors->first('image') }}</strong>
                                    </span>
                                @endif
                            </div>
                            <div class="form-group{{ $errors->has('status') ? ' has-danger' : '' }}">
                                <div class="input-group input-group-alternative mb-5">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text"><i class='fas fa-dollar-sign'></i></span>
                                    </div>
                                   <select class="form-control" name="status" class="form-control" required>
                                     <option value='0'>Free</option>
                                     <option value='1'>Paid</option>
                                   </select>
                                  </div>
                                @if ($errors->has('status'))
                                    <span class="invalid-feedback" style="display: block;" role="alert">
                                        <strong>{{ $errors->first('status') }}</strong>
                                    </span>
                                @endif
                            </div>

                                <div class="form-group{{ $errors->has('track_id') ? ' has-danger' : '' }}">
                                <div class="input-group input-group-alternative mb-5">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text"><i class="fa fa-road" aria-hidden="true" style="color:f46422"></i></span>
                                    </div>
                                   <select class="form-control" name="track_id" class="form-control" required>
                                
                                       <option value='{{$track->id}}'>{{$track->name}}</option>
                                    
                                   
                                     
                                   </select>
                                  </div>
                                @if ($errors->has('track_id'))
                                    <span class="invalid-feedback" style="display: block;" role="alert">
                                        <strong>{{ $errors->first('track_id') }}</strong>
                                    </span>
                                @endif
                            </div>
                               <div class="text-center">
                                <button type="submit" class="btn btn-block btn-success mt-5">{{ __('Create Course') }}</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>

        @include('layouts.footers.auth')
    </div>
@endsection

resources/views/admin/tracks/courses/edit.blade.php
@extends('layouts.app', ['title' => __('Edit course inside track determine')])

@section('content')
    @include('admin.users.partials.header', [
        'title' => __('Edit Course inside Track') . ' ',
        'description' => __('Hi '.auth()->user()->name .' can Edit Course inside Track'),
        'class' => 'col-lg-12'
    ])

    <div class="container-fluid mt--7">
        <div class="row">
            <div class="col-xl-12 order-xl-1">
                <div class="card bg-secondary shadow">
                    <div class="card-header bg-white border-0">
                        <div class="row align-items-center">
                            <h3 class="mb-0">{{ __('Edit Course inside Track') }}</h3>
                        </div>
                    </div>
<h1>Edit </h1>
                {{-- <form role="form" method="POST" action="{{ route('track.courses.update',$track,$course) }}" enctype="multipart/form-data"> --}}
                <form role="form" method="POST" action="/admin/track/{{$track->id}}/courses/{{$course->id}}" enctype="multipart/form-data">
                            @csrf
{{-- Title --}}             @method('PATCH')
                            <div class="form-group{{ $errors->has('title') ? ' has-danger' : '' }}">
                                <div class="input-group input-group-alternative mb-5">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text"><i class="ni ni-hat-3"></i></span>
                                    </div>
                                    <input class="form-control{{ $errors->has('title') ? ' is-invalid' : '' }}" placeholder="{{ __('title') }}" type="text" name="title" value="{{ $course->title }}" required autofocus>
                                </div>
                                @if ($errors->has('title'))
                                    <span class="invalid-feedback" style="display: block;" role="alert">
                                        <strong>{{ $errors->first('title') }}</strong>
                                    </span>
                                @endif
                            </div>
{{-- Title --}} 

                             <div class="form-group{{ $errors->has('link') ? ' has-danger' : '' }}">
                                <div class="input-group input-group-alternative mb-5">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text"><i class="fas fa-link"></i></span>
                                    </div>
                                    <input  value="{{ $course->link }}" class="form-control{{ $errors->has('link') ? ' is-invalid' : '' }}" placeholder="{{ __('link') }}" type="link" name="link" required>
                                </div>
                                @if ($errors->has('link'))
                                    <span class="invalid-feedback" style="display: block;" role="alert">
                                        <strong>{{ $errors->first('link') }}</strong>
                                    </span>
                                @endif
                            </div>
                                <div class="form-group{{ $errors->has('image') ? ' has-danger' : '' }}">
                                <div class="input-group input-group-alternative mb-5">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text"><i class='far fa-image' style="font-size:20px"></i></span>
                                    </div>
                                    
                                    <input class="form-control{{ $errors->has('image') ? ' is-invalid' : '' }}" placeholder="{{ __('image') }}" type="file" name="image" required>
                             
                                </div>
                                @if ($errors->has('image'))
                                    <span class="invalid-feedback" style="display: block;" role="alert">
                                        <strong>{{ $errors->first('image') }}</strong>
                                    </span>
                                @endif
                            </div>
                            <div class="form-group{{ $errors->has('status') ? ' has-danger' : '' }}">
                                <div class="input-group input-group-alternative mb-5">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text"><i class='fas fa-dollar-sign'></i></span>
                                    </div>
                                   <select class="form-control" name="status" class="form-control" required>
                                     <option value='0' {{($course->title==0)?'selected':''}}>Free</option>
                                     <option value='1' {{($course->title==1)?'selected':''}}>Paid</option>
                                   </select>
                                  </div>
                                @if ($errors->has('status'))
                                    <span class="invalid-feedback" style="display: block;" role="alert">
                                        <strong>{{ $errors->first('status') }}</strong>
                                    </span>
                                @endif
                            </div>

                                <div class="form-group{{ $errors->has('track_id') ? ' has-danger' : '' }}">
                                <div class="input-group input-group-alternative mb-5">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text"><i class="fa fa-road" aria-hidden="true" style="color:f46422"></i></span>
                                    </div>
                                   <select class="form-control" name="track_id" class="form-control" required>
                                
                                       <option value='{{$track->id}}'>{{$track->name}}</option>
                                    
                                   </select>
                                  </div>
                                @if ($errors->has('track_id'))
                                    <span class="invalid-feedback" style="display: block;" role="alert">
                                        <strong>{{ $errors->first('track_id') }}</strong>
                                    </span>
                                @endif
                            </div>
                               <div class="text-center">
                                <button type="submit" class="btn btn-block btn-success mt-5">{{ __('Create Course') }}</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>

        @include('layouts.footers.auth')
    </div>
@endsection